# Generated by Django 3.2.7 on 2021-09-02 16:30

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Regional_Abbreviation')),
                ('name', models.CharField(max_length=20, verbose_name='city_name')),
            ],
            options={
                'verbose_name': 'cities',
                'db_table': 'tb_cities',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user_info',
                'verbose_name_plural': 'user_info',
                'db_table': 'User',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_code', models.CharField(max_length=20, verbose_name='Hotel_code')),
                ('name', models.CharField(max_length=50, verbose_name='Hotel_name')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='app01.cities', verbose_name='hotels')),
            ],
            options={
                'verbose_name': 'hotels',
                'db_table': 'tb_hotels',
            },
        ),
    ]
